-----------------------------------
--	File: icons.lua
--	Description: K Neovim all icons
--	Author: Kevin
--	Last Modified: 07 May 2023, 15:50
-----------------------------------

-- Font: SauceCodePro Nerd Font Mono:13, v|i 92, n/n 90

return {
   kind = {
      Text = "",
      AltText = "",
      AltMethod = "",
      Function = "󰊕",
      Constructor = "",
      Method = "",
      AltFunction = "",
      AltConstructor = "",
      Field = "",
      Variable = "",
      Class = "",
      Interface = "",
      Module = "",
      Property = "",
      Unit = "",
      Value = "",
      Enum = "",
      Keyword = "",
      Snippet = "",
      Color = "",
      File = "",
      Reference = "",
      Folder = "",
      EnumMember = "",
      Constant = "",
      Struct = "",
      Event = "",
      Operator = "",
      Null = "󰟢",
      TypeParameter = "",
      Namespace = "",
   },
   type = {
      Array = "",
      Number = "",
      String = "",
      Boolean = "",
      Object = "",
   },
   documents = {
      File = "",
      Files = "",
      Folder = "",
      OpenFolder = "",
      FolderEmpty = "",
      default = "*",
   },
   git = {
      -- Change Type
      Add = "",
      Mod = "",
      Ignore = "",
      Remove = "",
      Rename = "",
      Diff = "",
      Repo = "",
      -- Status Type
      unstaged = "✗",
      staged = "",
      unmerged = "",
      untracked = "",
      conflict = "",
      ignored = "",
   },
   ui = {
      Lock = "",
      Circle = "",
      BigCircle = "",
      BigUnfilledCircle = "",
      Close = "",
      NewFile = "",
      Search = "",
      Lightbulb = "",
      Project = "",
      Dashboard = "",
      History = "",
      Comment = "",
      Bug = "",
      Code = "",
      Telescope = "",
      Gear = "",
      Package = "",
      List = "",
      SignIn = "",
      Check = "",
      Fire = "",
      Note = "",
      BookMark = "",
      Pencil = "",
      ChevronRight = "",
      ChevronLeft = "",
      BoldChevronRight = "",
      BoldChevronLeft = "",
      SlChevronRight = "⟩",
      SlChevronLeft = "⟨",
      SlArrowRight = "",
      AltSlArrowRight = "►",
      SlArrowLeft = "",
      AltSlArrowLeft = "◄",
      SlCircleRight = "",
      SlCircleLeft = "",
      SlEndLeft = "",
      SlEndRight = "",
      Table = "",
      Calendar = "",
      Download = "",
      Plugin = "󰀻",
      PluginManager = "",
      Uni = "",
      Health = "♥",
      Git = "",
      AppleSym = "",
      Version = "",
      Plus = "",
      Dev = "󰾰",
   },
   diagnostics = {
      Error = "",
      Warning = "",
      Information = "",
      Question = "",
      Hint = "󱧢",
      status_ok = "",
      status_not_ok = "",
   },
   misc = {
      Robot = "󰚩",
      Squirrel = "",
      Tag = "",
      Watch = "",
      GitHub = "",
   },
   bufferline = {
      modified_icon = "●",
      close = "",
      buffer_close_icon = "󰅙",
      left_trunc_marker = "",
      right_trunc_marker = "",
   },
   packer = {
      working_sym = "⟳",
      error_sym = "✗",
      done_sym = "✓",
      removed_sym = "-",
      moved_sym = "→",
      header_sym = "━",
   },
   lsp = {
      nvim_lsp = "[]",
      nvim_lua = "[]",
      luasnip = "[󰘦]",
      buffer = "[]",
      path = "[]",
      treesitter = "[]",
      latex_symbols = "[α]",
      emoji = "[]",
      calc = "[]",
   },
}
