-----------------------------------
--	File: icons.lua
--	Description: useful icons used in other modules and all neovim
--	Author: Kevin
--	Last Modified: 25 Apr 2024, 22:03
-----------------------------------

---NOTE:
---Font    : Fira Code : 12.5 v|i 92, n/n 90
---Fallback: Source Code Pro : 13 v|i 92, n/n 90
---Symbols : Symbols (Only) Nerd Font

local icons = setmetatable({
  kind = {
    Text = '',
    Function = '󰊕',
    Constructor = '',
    Method = '',
    Field = '',
    Variable = '',
    Class = '',
    Interface = '',
    Module = '',
    Property = '',
    Unit = '',
    Value = '',
    Enum = '',
    Keyword = '',
    Snippet = '',
    Color = '',
    File = '',
    Reference = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = '',
    Event = '',
    Operator = '',
    Null = '󰟢',
    TypeParameter = '',
    Namespace = '',
  },
  type = {
    Array = '',
    Number = '',
    String = '',
    Boolean = '',
    Object = '',
  },
  documents = {
    File = '',
    Files = '',
    Folder = '',
    OpenFolder = '',
    FolderEmpty = '',
    default = '*',
  },
  git = {
    Branch = ' ',
    -- Change Type
    Add = '',
    Mod = '',
    Ignore = '',
    Remove = '',
    Rename = '',
    Diff = '',
    Repo = '',
    -- Status Type
    unstaged = '*',
    staged = '',
    unmerged = '',
    untracked = '',
    conflict = '',
    ignored = '',
    deleted = '✗',
  },
  ui = {
    proc = ' ',
    term = ' ',
    disc = '󰋊',
    Copy = ' ',
    Db = '',
    Lock = '',
    Circle = '',
    SmallCircle = '',
    CircleEmpty = '○',
    BigCircle = '',
    BigUnfilledCircle = '',
    close = '',
    Quit = '󰿅 ',
    NewFile = '',
    Search = ' ',
    Lightbulb = '',
    Project = '',
    save = ' ',
    Dashboard = '',
    History = '',
    Comment = '',
    Bug = '',
    Code = '',
    Telescope = ' ',
    Gear = '',
    Package = '',
    List = '',
    SignIn = '',
    Check = '',
    Checkbox = '󰱑 ',
    Fire = '',
    Note = '',
    BookMark = '',
    Pencil = '',
    ChevronRightMedium = '❭',
    ChevronLeftMedium = '❭',
    ChevronRight = '',
    ChevronLeft = '',
    RightTriangle = '▶',
    LeftTriangle = '◀',
    UpTriangle = '▲',
    DownTriangle = '▼',
    BoldChevronRight = '',
    BoldChevronLeft = '',
    SlChevronRight = '⟩',
    SlChevronLeft = '⟨',
    SlArrowRight = '',
    AltSlArrowRight = '►',
    SlArrowLeft = '',
    AltSlArrowLeft = '◄',
    SlCircleRight = '',
    SlCircleLeft = '',
    SlEndLeft = ' ',
    SlEndRight = '',
    Table = '',
    Calendar = '',
    Download = '',
    Plugin = '󰀻',
    PluginManager = '',
    Uni = '',
    Health = '♥',
    Git = '',
    AppleSym = '',
    Version = '',
    Plus = '',
    Dev = '󰾰',
    WhichKeyChevron = '❯',
    WhichKeySep = '→',
    Orgmode = '',
    Query = '󱩾',
    Web = '󰖟',
    Bell = ' ',
    Messages = '󰍡 '
  },
  diagnostics = {
    Error = '',
    Warning = '',
    Information = '',
    Question = '',
    Hint = '󱧢',
    status_ok = '',
    status_not_ok = '',
  },
  misc = {
    Robot = '󰚩',
    Squirrel = '',
    Tag = '',
    Watch = '',
    GitHub = '',
  },
  bufferline = {
    modified_icon = '●',
    close = '',
    buffer_close_icon = '󰅙',
    left_trunc_marker = '',
    right_trunc_marker = '',
  },
  package_manager = {
    working_sym = '⟳',
    error_sym = '✗',
    done_sym = '✓',
    removed_sym = '-',
    moved_sym = '→',
    header_sym = '━',
  },
  lsp = {
    nvim_lsp = '[]',
    nvim_lua = '[]',
    luasnip = '[󰘦]',
    buffer = '[]',
    path = '[]',
    treesitter = '[]',
    latex_symbols = '[α]',
    emoji = '[]',
    calc = '[]',
    otter = '[⎆]'
  },
  debug = {
    run = '',
    continue = ' ',
    reload_continue = ' ',
    pause = '',
    stop = ' ',
    breakpoint = '',
    restart = ' ',
    disconnect = ' ',
    into = '',
    over = ' ',
    out = '󰆸',
    repl = ' ',
    rerun = ' ',
    eval = ' '
  }
}, {
    __index = function()
      return ' '
    end
  })

return icons