-----------------------------------
--	File: icons.lua
--	Description: K Neovim all icons
--	Author: Kevin
--	Source: https://github.com/kevinm6/nvim/blob/nvim/lua/user/icons.lua
--	Last Modified: 03/03/2022 - 21:22
-----------------------------------

-- Font: SauceCodePro Nerd Font Mono

return {
	kind = {
		Text = "",
		AltMethod = "",
		AltFunction = "",
		AltConstructor = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		-- Variable = "",
		Variable = "",
		Class = "",
		Interface = "",
		-- Module = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		-- Keyword = "",
		Snippet = "",
		-- Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	type = {
		Array = "",
		Number = "",
		String = "",
		Boolean = "蘒",
		Object = "",
	},
	documents = {
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
	},
	git = {
		-- unstaged = "✗",
  --   staged = "✓",
  --   unmerged = "",
  --   Rename = "➜",
  --   untracked = "★",
		Add = "",
		Mod = "",
		Ignore = "",
		Remove = "",
		Diff = "",
		Repo = "",
		-- Ignore = "◌",
		-- Rename = "",
	},
	ui = {
		Lock = "",
		Circle = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		Close = "",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = "",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = "",
		Note = "",
		BookMark = "",
		Pencil = "",
		-- ChevronRight = "",
		ChevronRight = "",
		ChevronLeft = "",
		BoldChevronRight = "",
		BoldChevronLeft = "",
		SlChevronRight = "⟩",
		SlChevronLeft = "⟨",
		SlArrowRight = "",
		AltSlArrowRight = "",
		SlArrowLeft = "",
		AltSlArrowLeft = "",
		Table = "",
		Calendar = "",
		Download = "",
		Plugin = "",
		Packer = "﬘",
		Uni = "",
		Health = "♥️",
		Git = "",
		AppleSym = "",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
	},
  bufferline = {
    modified_icon = "●",
    close = "",
    buffer_close_icon = "",
    left_trunc_marker = "",
    right_trunc_marker = "",
  },
}
