-----------------------------------
--	File: icons.lua
--	Description: K Neovim all icons
--	Author: Kevin
--	Source: https://github.com/kevinm6/nvim/blob/nvim/lua/user/icons.lua
--	Last Modified: 01/03/2022 - 09:56
-----------------------------------


-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
	kind = {
		Text = "",
		-- Method = "m",
		-- Function = "",
		-- Constructor = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		-- Variable = "",
		Variable = "",
		Class = "",
		Interface = "",
		-- Module = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		-- Keyword = "",
		Snippet = "",
		-- Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	type = {
		Array = "",
		Number = "",
		String = "",
		Boolean = "蘒",
		Object = "",
	},
	documents = {
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
	},
	git = {
		-- unstaged = "✗",
  --   staged = "✓",
  --   unmerged = "",
  --   Rename = "➜",
  --   untracked = "★",
		Add = "",
		Mod = "",
		Ignore = "",
		Remove = "",
		Diff = "",
		Repo = "",
		-- Ignore = "◌",
		-- Rename = "",
	},
	ui = {
		Lock = "",
		Circle = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		Close = "",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = "",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = "",
		Note = "",
		BookMark = "",
		Pencil = "",
		-- ChevronRight = "",
		ChevronRight = ">",
		Table = "",
		Calendar = "",
		Download = "",
		Packer = "練",
		Uni = "",
		Health = "♥️",
		Git = "",
		AppleSym = "",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
	},
}
